((tasks . (
     ("BILINGUAL-DOCUMENTATION-AUDIT" .
    ((priority . 9.0)
     (capabilities . (documentation translation audit policy))
     (origin . ecosystem)
     (context . "2026-09-08 ecosystem-wide language-debt audit (ecosystem/memory/LANGUAGE-DEBT-REGISTRY-2026-09-08.md): README.md opens with '## English' (line 39) before '## Українська' (line 55) -- English-first structural order violates language-policy.wsm's human-facing-order (ukrainian english german). Ukrainian content itself is present and complete, this is an ordering fix, not a translation gap.")
     (description . "Enforce the DOCUMENTATION LANGUAGE / МОВА ДОКУМЕНТАЦІЇ policy. Every human-authored markdown file (README, memory, plans, architecture, research) MUST have a substantive Ukrainian translation. Identify English-only documents and translate them. Do not translate machine identifiers or immutable historical records. Ensure every new or edited markdown document is bilingual.")))

("MYIDEA-SWARM-CONTRACT-01" . (
    (priority . 9.9)
    (description . "DONE 2026-08-18. Added repo.my ((id my-idea) (role observer-ide), exports ecosystem-status/evidence-matrix/knowledge-graph/swarm-status, imports language-contract/isa-contract/compatibility/evidence/repo-declarations, capabilities rust/clojurescript/tauri/gui/wasm, authorities ide-ux/workspace-security/evidence-visualization, non-authorities language-semantics/isa-design/compiler-internals/shiva-canon/paninian-ontology/hardware-implementation — same format as fpga-lisp/shiva-sutras/my-lisp-panini). Added ecosystem/README.md scaffold explaining why no ecosystem/imports/*.my files are populated (my-idea reads contracts/evidence live off disk via src-tauri/src/ecosystem/*.rs, not as cached claims). my-idea now shows as a declared node in its own Knowledge Graph tab instead of 'no repo.my'.")
    (done . t)
  ))
  ("MYIDEA-SWARM-DASHBOARD" . (
    (priority . 9.5)
    (description . "DONE 2026-08-19. New src-tauri/src/swarm_dashboard.rs parses swarm-node's (list-members) and (list-task-state) responses (same flat-field s-expr shape as repo.my) into a structured SwarmDashboard: per-member node id/presence/roles/capabilities, cross-referenced with currently-held open tasks from the task registry, plus overall open/completed counts. New swarm_dashboard Tauri command (separate from the existing raw-string swarm_status), new SWARM tab button and eco-view/swarm-dashboard-html renderer. Response shapes captured live from the running my-idea-1 swarm-node (13 members, 271+ task registry) via raw TCP before writing the parser; 3 cargo test unit tests assert against those real captured strings (not hand-idealized fixtures) — all pass. Not yet exercised through the actual Tauri command end-to-end (would need the shadow-cljs dev server + tauri dev, not run this session), only the parsing logic and the ClojureScript compile.")
    (done . t)
  ))
  ("SWARM-STATUS-DASHBOARD-FOLLOWUP" . (
    (priority . 1.0)
    (description . "Swarm-wide duplicate of MYIDEA-SWARM-DASHBOARD (done here 2026-08-19, commit c73038c — see that task's entry above for the real implementation). The swarm journal's own SWARM-STATUS-DASHBOARD task (defined via (define-task), not from this file) is still (holder my-idea-1) (completed nil) as of 2026-08-25 — confirmed live via (task-state (task SWARM-STATUS-DASHBOARD)). Next agent connecting as my-idea-1: please (complete-task (task SWARM-STATUS-DASHBOARD) (generation 1)) to close this near-duplicate (or check the current generation first with (task-state ...) if it has moved since).")
    (done . nil)
  ))
  ("MYIDEA-KNOWLEDGE-GRAPH" . (
    (priority . 9.0)
    (description . "Phase 1 DONE 2026-08-18 (see docs/knowledge-graph-design.md, commit b13443a): repo.my-derived node/edge graph tab, src-tauri/src/ecosystem/repo_graph.rs, knowledge_graph Tauri command, eco-view/knowledge-graph-html. Phase 2 (individual epistemic claims with PROVED/FALSIFIED/UNRESOLVED status, drift highlighting between shiva-sutras' claims-export.yaml and my-lisp-panini's ecosystem/imports/*.my) intentionally deferred, tracked in the design doc, not restated as a separate tasks.my entry.")
    (done . t)
  ))
  ("IDEA-PROTOCOL-DRIFT-FIX" . (
    (priority . 9.8)
    (description . "DONE 2026-08-18. Rewrote AGENTS.md's Coordination channels section to state plainly that swarm-node is the coordination layer (P2P mesh, no relaying) and :9999 is oracle-only (eval/parse/diagnose/contract-version) — matching fpga-lisp/AGENTS.md's wording. Added my-idea-1's own join/sync-tasks commands (port 9104) and a note that src-tauri/src/swarm.rs already talks to swarm-node directly, reading one line without waiting for EOF (unlike oracle.rs's one-shot :9999 client).")
    (done . t)
  ))
  ("IDEA-CONTRACT-VERSION-DRIFT-CHECK" . (
    (priority . 8.5)
    (description . "DONE 2026-08-18, no drift found. Grepped AGENTS.md/docs/README for hardcoded language-contract version claims: my-idea's own docs (system-observatory-status.md, system-observatory-vision.md) only reference language-contract.my/isa-contract.my/compatibility.my by filename, never hardcode a version number — contracts.rs reads them live at runtime via the my_lisp crate's own reader, not a saved-off number. The submodule's actual contract (external/my-lisp/language-contract.my) is currently (major . 2) (minor . 0). No fix needed; this repo was already doing it right.")
    (done . t)
  ))
  ("IDEA-SUBAGENT-DOCTRINE" . (
    (priority . 6.0)
    (description . "DONE 2026-08-18. Added 'Subagents and specialist models' section to AGENTS.md: independent subagents for audits/verification not parallel coding, never bias a verifier with the preferred answer, external specialist models (Sarvam etc.) are hypothesis sources not authoritative evidence, points to shiva-sutras/docs/sarvam-integration-guide.md for Sarvam operating details rather than duplicating them here.")
    (done . t)
  ))
  ("IDEA-APPIMAGE-XDG-UTILS" . (
    (priority . 4.0)
    (description . "PARTIAL 2026-08-18. Installed xdg-utils natively (sudo apt-get install -y xdg-utils) — /usr/bin/xdg-open now exists, confirmed via `which xdg-open`. Tried adding \"xdg-utils\" to manifest.scm's Guix package list first: broke pkg-config resolution for gio-sys (profile rebuild left pkg-config unfindable) — reverted, documented as a known-bad approach in manifest.scm's comments, native apt install is the working path (matches how Bun/build-essential/rustup are handled). NOT closing: re-running bun run tauri build afterward hit a *different*, pre-existing pkg-config failure (gio-sys/gobject-sys can't find pkg-config even with the reverted manifest) that also blocked the deb/rpm steps this time, unrelated to xdg-utils — see new IDEA-PKG-CONFIG-REGRESSION. Re-verify AppImage specifically once that's fixed.")
    (done . ())
  ))
  ("IDEA-PKG-CONFIG-REGRESSION" . (
    (priority . 9.5)
    (description . "ROOT-CAUSED 2026-08-18. bun run tauri build (and plain cargo check) intermittently fail with 'The pkg-config command could not be found' inside gio-sys/gobject-sys build scripts, specifically when entering the environment via `guix time-machine -C ../my-lisp/channels.scm -- shell -m manifest.scm` — repro'd 3x. Switching to plain `guix shell -m manifest.scm` (same manifest.scm, no time-machine channel pin) made cargo check pass clean on the first try, compiling the new ecosystem/repo_graph.rs module with zero errors. Root cause: guix time-machine re-fetches/re-authenticates the pinned channel (visible 'channel guix lacks an introduction' warning) and appears to rebuild a working profile whose pkg-config isn't correctly wired into cargo build-script subprocess PATH — a time-machine-specific profile-construction bug, not a missing package (pkg-config IS present and `which pkg-config` resolves fine in both cases). Workaround: prefer plain `guix shell -m manifest.scm` for iterative cargo check/build; reserve time-machine for when the rustc-too-old blocker actually requires the pinned rust 1.93.0 (see AGENTS.md's rustc-too-old section) — document this distinction in AGENTS.md.")
    (done . t)
  ))
  ("IDEA-PLAYWRIGHT-BROWSER-SETUP" . (
    (priority . 4.0)
    (description . "bun run test fails 1 of 37 subtests on a fresh environment ('Standalone web artifact does not stack overflow on 100k list', tests/smoke.test.mjs:205) with 'browserType.launch: Executable doesn't exist ... chrome-headless-shell'. Needs 'bunx playwright install' as a documented one-time setup step (AGENTS.md and/or CI) so clean-install verification doesn't need manual intervention to fully pass. DONE: commit a865ed5 (2026-08-22) documents the step in AGENTS.md:277-280, verified end-to-end (build EXIT=0, npm test 37/37 PASS); CI (.github/workflows/ci.yml:40) already runs 'bunx playwright install chromium --with-deps'.")
    (done . t)
  ))
  ("IDEA-PUSH-BUN-MIGRATION" . (
    (priority . 9.0)
    (description . "DONE 2026-08-18. Pushed cb2ec03 to origin/main and watched GitHub Actions run 32124245188 to completion: all steps green, including bun install --frozen-lockfile, bun run build, bun run test, bun run check, Playwright browser install. First real (non-local) confirmation that the Bun migration works end to end in CI.")
    (done . t)
  ))
  ("IDEA-RELEASE-PS1-JSON-VERIFY" . (
    (priority . 3.0)
    (description . "scripts/release.ps1 was changed to bump package.json's version via Get-Content|ConvertFrom-Json/ConvertTo-Json instead of npm.cmd version (package-lock.json is gone). Never dry-run tested on Windows PowerShell 5.1 — ConvertTo-Json's property ordering/formatting/depth-handling on this specific package.json (nested devDependencies, scripts) should be diffed against the original file structure to confirm it doesn't reorder keys or mangle anything before the next real release relies on it.")
    (done . ())
  ))
  ("IDEA-REAL-ECOSYSTEM-INTEGRATION-TEST" . (
    (priority . 5.0)
    (description . "Per docs/manus-ai-review-analysis.md (2026-08-18, analyzing external Manus AI reviews): tests/eco-panel.test.mjs only exercises the Playwright UI against mocked data, so it proves layout, not correctness of ecosystem_status/knowledge_graph's actual data derivation from disk. Add a real native Tauri integration test: build a temporary sibling-repo directory layout (fake my-lisp/fpga-lisp/cml/shiva-sutras/my-lisp-panini with known repo.my/contract files), call ecosystem::status()/ecosystem::knowledge_graph() directly, assert on the structured output. Cheap, concrete, catches real regressions in the repo_graph.rs/contracts.rs/evidence.rs parsers that mocked frontend tests cannot.")
    (done . ())
  ))
  ("IDEA-SARVAM-VERIFY-I18N-STRINGS" . (
    (priority . 7.0)
    (description . "DONE (first pass) 2026-08-19. See docs/sarvam-i18n-verification.md: checked 4 of ~20+ i18n.cljs strings (uk+de :ast label, uk+de amber theme name) via cold single-fact Sarvam calls, no max_tokens. Finding: both uk 'Лабораторія мов / AST' and de 'Sprachlabor / AST' independently got the same stylistic note (grammatically correct, but a literal-metaphor translation of 'Language Lab') — kept as-is, a deliberate name choice matching the product's own 'Language Lab' terminology, not a translation error; documented as a recorded disagreement per the task's own instruction, not silently accepted or silently changed. Theme names (Бурштин/Bernstein for Amber) confirmed idiomatic, no issue. Remaining ~16 strings (other UI labels, other theme names) not yet sampled — future pass if desired, not blocking.")
    (done . t)
  ))
  ("IDEA-PRODUCT-RESET-ADR" . (
    (priority . 10.0)
    (description . "Record the owner-ratified reset: my-idea is a simple WSM/Tauri IDE with an Open/Edit/Build/Run/Stop/Output loop; Observatory and swarm control belong to tauricode. Preserve old vision as historical, update AGENTS/README/repo.my, define the reuse map and evidence ladder.")
    (done . t)
  ))
  ("IDEA-REMOVE-OBSERVER-UI" . (
    (priority . 9.8)
    (depends-on . (IDEA-PRODUCT-RESET-ADR))
    (description . "Remove Observatory, Oracle, Compare, Swarm, Knowledge Graph and SWARM controls from the primary toolbar and delete obsolete UI routing/tests. Do not delete backend code until Tauricode ownership and any historical evidence are checked. Visible command means a working end-to-end path.")
    (done . t)
  ))
  ("IDEA-NEW-FILE-SAVE" . (
    (priority . 9.7)
    (depends-on . (IDEA-PRODUCT-RESET-ADR))
    (description . "Make New File -> Save work inside the selected workspace. Add a root-contained create path that canonicalizes the existing parent, rejects traversal/symlink escape and never overwrites without an explicit decision. Add native tests for create, traversal rejection and existing-file behavior.")
    (done . t)
  ))
  ("IDEA-BUILD-PROCESS-CONTRACT" . (
    (priority . 9.6)
    (depends-on . (IDEA-PRODUCT-RESET-ADR))
    (description . "Define and implement the Tauri-side build process contract: one active run per workspace, executable plus argv (no shell concatenation), fixed cwd, structured stdout/stderr events, idle/running/succeeded/failed/cancelled states and bounded cancellation. Windows cancellation must terminate the descendant process tree.")
    (done . t)
  ))
  ("IDEA-BUILD-OUTPUT-UI" . (
    (priority . 9.2)
    (depends-on . (IDEA-BUILD-PROCESS-CONTRACT IDEA-REMOVE-OBSERVER-UI))
    (description . "Replace the generic secondary/Observatory pane with one bottom Build Output panel. Render ordered stdout/stderr events, active command profile, exit state and one actionable missing-tool diagnostic. Add UI tests against the real event schema, not arbitrary strings.")
    (done . ())
  ))
  ("IDEA-STOP-BUILD" . (
    (priority . 9.1)
    (depends-on . (IDEA-BUILD-PROCESS-CONTRACT IDEA-BUILD-OUTPUT-UI))
    (description . "Wire the Stop action to bounded process-tree cancellation and prove that no child compiler/dev-server remains alive. Stop is hidden or disabled when no run is active; cancellation is distinct from failure.")
    (done . ())
  ))
  ("IDEA-WSM-CLI-ADAPTER" . (
    (priority . 9.4)
    (depends-on . (IDEA-BUILD-PROCESS-CONTRACT))
    (description . "Add an explicit WSM project adapter using only commands actually supported by the authoritative my-lisp CLI and WsmLS/my-lisp LSP. Provide Run and Check/diagnostics without reimplementing parsing or semantics in my-idea. Do not expose a universal CML Compile button until CML-STABLE-CLI-CONTRACT exists.")
    (done . ())
  ))
  ("IDEA-LSP-CLIENT-TRANSPORT" . (
    (priority . 9.65)
    (depends-on . (IDEA-PRODUCT-RESET-ADR))
    (description . "Implement one persistent Tauri-side LSP/JSON-RPC stdio client with Content-Length framing, request correlation, server notifications, workspace-root lifecycle and bounded shutdown. It must accept executable+argv profiles, not shell strings, and expose no language semantics of its own.")
    (done . t)
  ))
  ("IDEA-WSM-LSP-ADAPTER" . (
    (priority . 9.6)
    (depends-on . (IDEA-LSP-CLIENT-TRANSPORT))
    (description . "Route .wsm/.my/.lisp documents to the authoritative `my-lisp lsp` stdio server. Wire diagnostics, completion, hover, symbols and definition capabilities supported by WsmLS into CodeMirror without duplicating its parser or builtin registry.")
    (done . ())
  ))
  ("IDEA-RUST-ANALYZER-ADAPTER" . (
    (priority . 9.55)
    (depends-on . (IDEA-LSP-CLIENT-TRANSPORT))
    (description . "Route .rs documents to the installed official Rust LSP implementation `rust-analyzer`. Detect Cargo workspace root, report missing rust-analyzer/rust-src actionably, and wire diagnostics, completion, hover, symbols and definition through the same CodeMirror adapter as WsmLS.")
    (done . ())
  ))
  ("IDEA-TAURI-BUILD-ADAPTER" . (
    (priority . 9.3)
    (depends-on . (IDEA-BUILD-PROCESS-CONTRACT))
    (description . "Detect a Tauri project through package.json, src-tauri/Cargo.toml and Tauri config. Implement fixed Check/Dev/Build profiles using the repository's Bun/Cargo/Tauri contract, frozen dependency installation, fixed cwd, argv arrays, live output and typed missing-tool errors.")
    (done . ())
  ))
  ("IDEA-SELF-BUILD-WITNESS" . (
    (priority . 9.0)
    (depends-on . (IDEA-TAURI-BUILD-ADAPTER IDEA-BUILD-OUTPUT-UI IDEA-STOP-BUILD IDEA-NEW-FILE-SAVE))
    (description . "Open the my-idea checkout in my-idea and build it through the same public Tauri adapter used for other projects. Record source commit, toolchain versions, command profile, exit state, bundle path and SHA-256 digest. Do not call this verified until the artifact is produced by the IDE-driven path.")
    (done . ())
  ))
)))
